### ISSUE TITLE
the version of the package

### ISSUE THREAD

**Issue by AFVzhou** [StatXzy7/PTransIPs#1]
Hello, can you upload the version requirements of the installation package，Thank you very much

**Comment by JZSAWYER** [comment]
Thank you for your attention, we have uploaded the requirements file, we recommend using python version 3.9, with conda to mange your environments.
Installing it directly will work, we are planning to update the README soon after.
If there is any other problems, feel free to ask.

**Comment by JZSAWYER** [comment]
> Hello, can you upload the version requirements of the installation package，Thank you very much

Thank you for your attention, we have uploaded the requirements file, we recommend using python version 3.9, with conda to mange your environments.
Installing it directly will work, we are planning to update the README soon after.
If there is any other problems, feel free to ask.

**Comment by JZSAWYER** [comment]
> Hello, can you upload the version requirements of the installation package，Thank you very much

Just let you know that we have updated the installation guide on the requirements of the packages, you may check README to help you install.
BTW, If you don't have any further questions, we are deciding to close this issue, thanks!

**Comment by AFVzhou** [comment]
Thank you very much
