### ISSUE TITLE
No Such File

### ISSUE THREAD

**Issue by AFVzhou** [StatXzy7/PTransIPs#2]
Hello, the link to download PTransIPs model is invalid, could you please resend it? And the.\model\Y_train and.\model\Y_test files are not found in the project,  is there any steps I am missing? I am looking forward to your reply, thank you very much.

**Comment by StatXzy7** [comment]
Hi, we check the link in onedrive is still valid, https://1drv.ms/f/s!AqzWnkSOWHpvhxMUDCjM9KFpz50O?e=N23jEn
For .\model\Y_train and.\model\Y_test folders, please create them manually if not work.

**Comment by JZSAWYER** [comment]
> Hello, the link to download PTransIPs model is invalid, could you please resend it? And the.\model\Y_train and.\model\Y_test files are not found in the project, is there any steps I am missing? I am looking forward to your reply, thank you very much.

Hi, we believe the problem is fixed. So we are deciding to close the issue.
